export const GET_ALL_PROGRAMS = "GET_ALL_PROGRAMS";
export const GET_GENRES = "GET_GENRES";
export const GET_PLATFORMS = "GET_PLATFORMS";
export const GET_PROGRAM_DETAIL = "GET_PROGRAM_DETAIL";
export const FILTER_PROGRAMS_BY_PLATFORM = "FILTER_PROGRAMS_BY_PLATFORM";
export const FILTER_PROGRAMS_BY_GENRE = 'FILTER_PROGRAMS_BY_GENRE';
export const FILTER_PROGRAMS_COMBINED = 'FILTER_PROGRAMS_COMBINED';
export const GET_BYNAME = "GET_BYNAME";

