export const GET_ALL_PROGRAMS = "GET_ALL_PROGRAMS";
export const GET_PROGRAM_DETAIL = "GET_PROGRAM_DETAIL";
export const FILTER_PROGRAMS_BY_PLATFORM = "FILTER_PROGRAMS_BY_PLATFORM";
export const FILTER_PROGRAMS_BY_GENRE = 'FILTER_PROGRAMS_BY_GENRE';

